apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: vdinicola-service-dependency
  description: |
    Vince's example service which has something to do with APIs and database.
  links:
    - title: Website
      url: http://harness.io
  annotations:
    github.com/project-slug: vdinicola/idp-workshop
    backstage.io/techdocs-ref: dir:../
    lighthouse.com/website-url: https://harness.io
#    harness.io/services: |
#      paymentService: https://app.harness.io/ng/account/IFG41DWvSnaRLOVNB2uesg/cd/orgs/demoorg/projects/paymentservice/services/paymentservice
#    harness.io/pipelines: |
#      paymentService: https://app.harness.io/ng/account/IFG41DWvSnaRLOVNB2uesg/cd/orgs/demoorg/projects/paymentservice/pipelines/harnesscicd/pipeline-studio?storeType=INLINE
#  labels:
#    key1: value1
  tags:
    - vdinicola
spec:
  type: service
  owner: TeamA
  lifecycle: experimental
#  system: Demo
  dependsOn:
    - component:default/vdinicola-service
#  consumesApis:
#    - user-api
#  providesApis:
#    - example-api
